= Упражнение 2: Обектно-ориентирано програмиране с Java (втора част)

Да се имплементира TODO list

== Изисквания

Програмата трябва да може да пази списък със задачи в масив.
Една задача има следните атрибути:

* Заглавие (string)
* Описание (string)
* Статус (стойност от следните: `INITIAL`, `IN PROCESS`, `DONE`)
* Приоритет (цяло число от 1 до 5)
* Краен срок (дата от календара, без час)

При стартиране на програмата да се извеждат нейните опции:

----
Изберете опция:

1) Всички задачи подредени по приоритет
2) Задачи със статус IN PROCESS
3) Задачи, които да се завършат в следващите три дни
4) Изход

Вашият избор (1-4): _
----

При избор на дадена опция да се извежда нейното съдържание и след него да се извежда отново менюто.
Това да се повтаря докато не бъде избрана опция _Изход_

При стартирането на програмата, в паметта трябва да се зареди списък с поне 7 примерни задачи с разнообразен приоритет, статус и краен срок.

=== Задачите подредени по приоритет

Тук трябва да се извежда списъкът с *всички* задачи (независимо от статуса им).
Списъкът трябва да включва тяхното заглавие, статус, приоритет и краен срок (без описание).
Те трябва да са подредени по приоритет, като тези с по-висок такъв се извеждат преди тези с по-нисък.
Редът на задачи с равен приоритет не е от значение.
Най-високият приоритет е 1, а най-нисък е 5.

=== Задачи със статус IN PROCESS

Списъкът трябва да е със същия формат като в предишната опция.
Разликата е, че се извеждат само задачите, чийто статус е `IN PROCESS`.
Те отново трябва да бъдат подредени по приоритет.

=== Задачи, които да се завършат в следващите три дни

Форматът и подредбата на списъка се запазва.
Разликата е, че задачите трябва да са със статус `IN PROCESS` и `INITIAL`.
Също трябва да се покажат тези, чийто краен срок е в някой от следващите три дни: днес, утре, вдругиден и по-вдругиден.

== Допълнителни разяснения

Използвайте enum за представянето на статусите

За представяне на крайния срок за дадена задача използвайте някой подходящ клас от `java.time` пакета

Ако се въведен невалидна опция (число извън 1-4 или някакъв друг символ), да се хвърля Exception, който да се обработва и да се извежда съобщение за грешка.
След това да се изведе отново менюто с опциите и подканянето за избор на една от тях

За сортиране на задачите в масива използвайте някой от `Arrays.sort()` методите.
За да сработи той, трябва вашият клас описващ задачата да имплементира интерфейса `Comparable`.
Например:

[source,java]
----
public class Task implements Comparable<Task> {

    // Task atributes

    @Override
    public int compareTo(Task otherTask) {
        // Implementation
    }
}

----

Конструкцията `Comparable<Task>` ще бъде обяснена на следващите лекции.
За момента я използвайте наготово, така както иползвахте `public static void main` без да сме ви разкали какво е _static_.
Със спецификацията на метода `compareTo` се запознайте от неговия JavaDoc.

Класовете в `java.time` пакета имат удобни методи `plus` и `minus`, които ви връщат обекти представляващи дни след или преди зададения.
