= Упражнение 1: Увод в програмирането и обектно-ориентирано програмиране с Java (първа част)

Да се имплементира играта морски шах.

== Правила на играта

Играта се играе върху дъска с 3х3 полета от двама играчи, като всеки избира свой знак (X или O).
Започва играчът избрал X, като играчите се редуват да поставят своя знак в празните полета.
Целта е да се подредят три знака в един ред, една колона или по диагонал.
Който пръв подреди тройка, е победител.

== Условие на задачата

Преди да започнат играта, играчите се уговарят с какъв знак ще играят (X или O).
При всеки ход компютърът извежда текущата дъска, като свободните полета са означени със съответната цифра от 1 до 9, а заетите със съответния знак.
Например на първия ход, при абсолютно празна дъска, програмата трябва да извежда следната графика:

----
 1 | 2 | 3
---|---|---
 4 | 5 | 6
---|---|---
 7 | 8 | 9
----

Под дъската програмата трябва да подканя играча, който е на ход да избере номера на позицията, на която иска да постави своя знак:

----
Играч X, моля въведете своя ход (1-9)> _
----

Ако полето вече е заето или се въведе символ различен от числата от 1 до 9, програмата трябва да изведе съобщение за грешка.
В противен случай, трябва да изведе отново дъската, този път с попълнена позиция със съответния знак и подканяне към следващия играч:

----
Играч X, моля въведете своя ход (1-9)> 5

 1 | 2 | 3
---|---|---
 4 | X | 6
---|---|---
 7 | 8 | 9

Играч O, моля въведете своя ход> _
----

Когато играта приключи с победа за някой от играчите или равен резултат, на екрана трябва да се изведе съобщение за края и програмата трябва да приключи своето изпълнение:

----
Победител е играч X!
----

== Подсказки

Задачата изисква потребителите да въвеждат своя избор от конзолата.
В Java най-лесно това става като се използва `java.util.Scanner` класа.
Например, за да се прочете нещо от клавиатурата и да се запише в променливата `input`, трябва да се напише следния код:

[source,java]
----
Scanner scanner = new Scanner(System.in);
String input = scanner.nextLine();
----

== Допълнителни задачи

. Ако играта попадне в ситуация, че няма как да има победител, то програмата трябва да завърши изпълнение още тогава.
. Да се напише програма, която да играе срещу участника.
