= Упражнение 4: Управление на вход и изход

Да се имплементира четене на текст на "шльокавица" от конзолата и негова трансформация до кирилица

== Четене от клавиатурата

Първата задача е да се чете текст от конзолата.
Текстът трябва да се въвежда на "шльокавица" като нека да имаме следната таблица на съответствие:

[options="header"]
|================================================
| Шльокавица | Кирилица | | Шльокавица | Кирилица

| a          | а |
| b          | б

| w          | в |
| g          | г

| d          | д |
| e          | е

| v          | ж |
| z          | з

| i          | и |
| j          | й

| k          | к |
| l          | л

| m          | м |
| n          | н

| o          | о |
| p          | п

| r          | р |
| s          | с

| t          | т |
| u          | у

| f          | ф |
| h          | х

| c          | ц |
| `          | ч

| [          | ш |
| ]          | щ

| y          | ъ |
| x          | ь

| \          | ю |
| q          | я
|================================================

Освен горните символи се допускат интервали, препинателни знаци, числа и нови редове.

Въвеждането на текст от конзолата става докато не бъде срещната думата _kraj_.

След като бъде трансформиран, текстът трябва да бъде записан обратно в изходен файл, този път на кирилица.
Новите редове въведени на конзолата, трябва да бъдат отразени и в изходния файл.

TIP: По възможност имплементирайте трансформацията в поток по подобие на `UpperCaseReader`, който ви беше демонстриран на лекцията

== Броене на думи

Записаният в предишната точка файл да бъде прочетен обратно в паметта.
След това на екрана да се изведе броят на всички думи в него.

TIP: При четене може да игнорирате препинателните знаци и числата, а новите редове да трансформирате в интервали.
И след това да използвате някой от методите на `String` класа, за да видите на колко думи би се разделил оригиналния текст, ако за разделител изберем интервал.

== Честотен анализ на буквите

Да се направи честотен анализ на всички букви във файла с текста на кирилица.
Интервалите, числата, препинателните знаци и новите редове да се игнорират.

Резултатът да се съхрани в map, чийто ключ е съответната буква от азбуката, а стойност е колко пъти се е срещала тя в текста.
На екрана да се изведат седемте най-често използвани букви заедно с честотата на тяхното използване, подредени в низходящ ред.
