= Упражнение 5: Работа с файлове и автоматично тестване

Ще рефакторираме и разширим фукнционалността на TODO list приложението, което разработихме на link:https://github.com/slbedu/javase8-2016/tree/master/lab02[второто упражнение] и ще добавим автоматични тестове.

== Изисквания

Припомнете си изискванията към TODO list приложението. Ще започнем от съществуващото решение (вашето, или link:https://github.com/slbedu/javase8-2016/tree/master/lab02/todolist/src/bg/uni/sofia/fmi/todolist[това], което сме качили ние).

Ще разширим функционалността на приложението, като добавим опции за импортиране и експортиране на задачи от файл в link:https://en.wikipedia.org/wiki/Comma-separated_values[CSV формат]. Всяка задача се описва на отделен ред във файла, като стойностите на отделните параметри се разделят със запетаи (приемаме за простота, че никоя стойност не съдържа запетая).

----
Изберете опция:

1) Всички задачи подредени по приоритет
2) Задачи със статус IN PROCESS
3) Задачи, които да се завършат в следващите три дни
4) Импортиране на задачи от файл
5) Експортиране на задачи във файл
6) Изход

Вашият избор (1-6): _
----

При избор на опции 1-3 да се извежда съответният резултат и след него да се извежда отново менюто.
При избор на опция 4, потребителят въвежда името (с пълния път) на файла, задачите се зареждат в паметта и се извежда пак менюто.
При избор на опция 5, потребителят въвежда името (с пълния път) на файла, където да се запишат текущите задачи. Ако посоченият файл съществува, да се създаде негово копие, след което се записва текущото съдържание на списъка от задачи и се извежда менюто.
Това да се повтаря докато не бъде избрана опция _Изход_

=== Тестове

Първо създайте unit тестове за функционалността на опции 1-3.
На втора стъпка, създайте тестове и за опции 4 и 5, те са една идея по-сложни.
При писането на тестове, може да се наложи да рефакторирате кода на приложението.

=== Допълнително условие

При избор на опция 5, ако файлът съществува и се създаде копие, ако съществуващият файл е последно модифициран преди повече от 24 часа, да се премести в архив с име Backup в папка с име текущата дата(ден.месец.година).

== Подсказки

При зареждане на задачите от файла, може да използвайте метода на String класа

`String[] split(String regex)`

За копиране на файл, използвайте метода на Files класа

`Path copy(Path source, Path target, CopyOption... options)`

== Стъпки за настройка на проекта

1. Импортнете проекта в ИДЕ-то
* File -> Import -> Existing Projects into workspace

2. При нужда оправете билд пътя да сочи към сдк-то с правилно име.
* Десен бутон в/у проекта Build Path -> Configure Build Path -> Libraries ако сдк-то свети червено премахнете го и добавете версия 1.8

3. Създайте нова сорс директория наречена "tests"
* Десен бутон в/у проекта -> new -> Source Folder

4. В сорс директорията създайте подходящи пакети и вътре напишете тестовете

