= Упражнение 8: Основи на мрежовото програмиране

== Условие на задачата

Да се имплементира многонишково клиент-сървър приложение, което представлява `echo` сървър. Приложението има клиентска и сървърна част. Клиентът се свързва към сървъра с помощта на класа `java.net.Socket` и изпраща текстови съобщения, прочетени от стандартния вход. Сървърът слуша на определен порт за конекции от един или повече клиенти, чете от потока на `socket`-а и изпраща обратно прочетеното към съответния клиент. Клиентът затваря връзката към сървъра, когато от стандартния вход бива прочетено `quit`. 

== Допълнителни задачи

. Реализирайте клиентска команда `count`, при получаването на която сървърът отговаря с броя на текущо активните клиентски конекции.
Уверете се, че в кода ви няма синхронизационни проблеми.
. Реализирайте клиентска команда `download <URI> <path>`, където `URI` е адрес на изображение в Интернет, а `path` е директория. При получаване на командата сървърът изтегля изображението и го запазва в зададената директория.
. Направете алтернативна имплементация на сървъра в отделен пакет, като използвате java.nio пакета.