= Упражнение 3: Параметризирани типове и колекции

Да се имплементира играта link:https://en.wikipedia.org/wiki/Bulls_and_Cows[крави и бикове].

== Правила на играта

Крави и бикове е логическа игра за отгатване на цифри. Играе се от двама противници, като всеки се стреми да отгатне тайното число, намислено от другия. След всеки ход противникът дава броя на съвпаденията.
Тайните числа са четирицифрени, като цифрите не трябва да се повтарят. След това, последователно един след друг, играчите задават въпрос с предположение за числото на противника. Противникът отговаря, като посочва броя на съвпаденията - ако дадена цифра от предположението се съдържа в тайното число и се намира на точното място, тя е „бик“, ако пък е на различно място, е „крава“. Това се повтаря докато единият от играчите не отгатне противниковото число, или не се предаде.
В нашия вариант на играта ще играем срещу компютъра.

Например, ако компютърът си е намислил числото 4761, за следните ни предположения ще получим подобни отговори:

----
0438 --> 1 крава
4067 --> 2 бика и 1 крава
1674 --> 4 крави
4761 --> 4 бика
----

В различен вариант на играта се отгатва комбинация от N символа (напр. букви, цифри или произволни елементи).

== Изисквания

При стартиране на играта, играчът въвежда дължината на предположението.
Помислете за добър ООП дизайн, който да позволи реализиране на максимално __generic__ вариант на  играта, както и за подходящо приложение на параметризирани типове и колекции.

_Примерен вход (при намислена комбинация 958210):_
----
Въведете дължината на вашето предположение>6
Въведете вашето предположение>457901
----

_Примерен изход:_
----
1 бик, 3 крава
----
'''
_Примерен вход (при намислена комбинация a@2S):_
----
Въведете дължината на вашето предположение>4
Въведете вашето предположение>S@2v
----

_Примерен изход:_
----
2 бика, 1 крава
----

== Допълнителни задачи

. Реализирайте версия на играта, в която вие си намисляте комбинация и компютърът отгатва вашето предположение с възможно най-малък брой опити.
