= Упражнение 6: lambda изрази и stream-ове

Да се зареди в паметта списък от филми от файл и да се извършат определени справки с тях и с участващите актьори.

== Пояснения

Import-нете проекта от папката `movies` в IDE-то.

* Ако използвате Eclipse, изпълнете `File → Import → General → Existing Project into Workspace`
* Ако използвате NetBeans, изпълнете `File → Import Project → Eclipse Project → Import Project Ignoring Project Dependencies`
* Ако използвате IntelliJ IDEA, изпълнете `File → New → Project From Existing Sources`

Той се състои от три класа и един ресурс. Класовете се намират в папката `src`, а ресурсът - в папката `resources`.

`Actor` класът описва един актьор с неговото първо и второ име.
`Movie` класът описва даден филм - заглавие, година на издаване и актьорски състав (под формата на списък).
`MovieExplorer` е класът, в който ще решавате дадените задачи.
Той има един main метод и няколко помощтни метода, които още не се използват.

`resources` папката съдържа един текстов файл.
Той е зареден от http://introcs.cs.princeton.edu/java/data[страницата на Robert Sedgwick]
Всеки ред от него представлява един филм, като форматът е следният:

----
<заглавие> (<година на издаване>)/<фамилия>, <първо име>[/<фамилия>, <първо име>[/....]]
----

Задачата ще е да се заредят филмите от файла и да се изпълнят седем справки с тях.

== Задачи

=== Задача 1: Да се заредят филмите от файла

Това, което трябва да направите, е да заредите редовете на файла в паметта и за всеки един от тях да извикате написания предварително за вас метод `addMovie()`.
Той приема два параметъра - текущият списък с филмите и `String` представляващ един ред от входния файл.

Заредете всички редове от файла.
За всеки един от тях изпълнете дадения метод.
Подайте предварително създадения `movies` списък, методът ще добавя на всяко извикване parse-натия филм към него.

=== Задача 2: Да се намери броят на филмите излезли през 2003 година

За тази и за следващите задача ще ви трябва stream върху списъка с филми.
Тук по-конкретно ще трябва да отсеете само филмите, чиято година на издаване е 2003 и да намерите техния брой.
Междинната операция на `java.util.Stream` трябва да връща stream от елементи със същия тип, но с по-малък брой.
Помислете коя е тя и коя ще е терминалната операция.

=== Задача 3: Намерете първият филм, който съдържа _Lord of the Rings_ в заглавието си

Ако такъв филм бъде намерен, да се изпечата неговото заглавие и година на издаване.
Ако такъв филм не е намерен, да се хвърли `IllegalArgumentException`.

Тук междинната операция е същата като в предишната задача, но терминалната е различна.
Използвайте `Optional` API-то на връщаната стойност от терминалната операция, за да обработите двата случая: на открит и неоткрит филм с това заглавие.

=== Задача 4: Изведете на екрана всички филми, сортирани според годината на производство

Тук междинната операция ще трябва да промени типа на stream-а на сортиран.
Терминалната операция просто ще трябва да извежда на екрана всички филми според зададения критерий за сортиране.

=== Задача 5: Намерете първата и последната година в списъка с филмите

Тук междинната операция ще трябва да върне stream със същия брой елементи, но с различен тип.
И то типът на елементите трябва да бъде примитивен.

=== Задача 6: Изведете филмите групирани според тяхната година на излизане

Тук няма да има междинна операция.
Крайната операция ще трябва да collect-не елементите в `Map`, като груповият признак, според който се определя key-а, е годината на излизане

=== Задача 7: Да се изведе на екрана списъкът с всички актьори

Тук имаме stream от филми.
За всеки елемент от този stream можем с една трансформация на списъкът от актьорите да получим stream от актьори.
Така реално получаваме stream от stream-ове от актьори.
Необходимо е вместо да имаме два вложени stream-а, да остане един.
И този stream да се събере в подходяща колекция, при която да не се допускат повторения.

=== Задача 8: Да се намерят всички филми с Kevin Spacey

Тук междинната операция трябва да връща stream от същия тип (`Movie`), който обаче да сочи към по-малък брой филми.
Условието даден филм да попадне в този списък е неговият списък с актьори да съдържа Kevin Spacey.
Потърсете някаква stream операция, която проверява дали даден stream съдържа определен елемент.